# Generated by Django 3.0.5 on 2021-02-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210222_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['client', 'category'], 'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.RenameField(
            model_name='email',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='client_id',
            new_name='client',
        ),
    ]
