# Generated by Django 3.0.5 on 2021-02-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210228_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
    ]
