# Generated by Django 3.0.5 on 2021-02-28 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20210228_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='category',
            field=models.CharField(blank=True, choices=[(None, 'Выберите тип номера телефона'), ('w', 'Рабочий телефон'), ('h', 'Домошний телефон'), ('m', 'Мобильный телефон'), ('o', 'другой...')], max_length=1, null=True, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Interplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, choices=[(None, 'Выберите вид обращения'), ('app', 'Заявка'), ('let', 'Письмо'), ('sit', 'Сайт'), ('ini', 'Инициатива компании')], max_length=3, null=True, verbose_name='Вид обращения')),
                ('descript', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('rating', models.BooleanField(verbose_name='Оценка взаимодействия')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project', verbose_name='Проект')),
            ],
        ),
    ]
