# Generated by Django 3.0.5 on 2021-03-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210228_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='author',
        ),
    ]
