# Generated by Django 3.0.5 on 2021-03-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_client_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='descript',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о клиенте'),
        ),
    ]
