# Generated by Django 3.0.5 on 2021-03-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210301_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='interplay',
            name='type_comm',
            field=models.CharField(choices=[('comm', 'Комментарий'), ('task', 'Задача'), ('lett', 'Письмо'), ('bell', 'Звонок'), ('even', 'Событие')], default='comm', max_length=4, verbose_name='Тип взаимодействия'),
        ),
        migrations.AlterField(
            model_name='interplay',
            name='channel',
            field=models.CharField(blank=True, choices=[(None, 'Выберите канал обращения'), ('app', 'Заявка клиента'), ('let', 'Письмо клиента'), ('sit', 'Сайт компании'), ('ini', 'Инициатива компании')], max_length=3, null=True, verbose_name='Канал обращения'),
        ),
    ]
