# Generated by Django 3.0.5 on 2021-03-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_interplay_date_comm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interplay',
            options={'ordering': ['date_comm'], 'verbose_name': 'Взаимодействие', 'verbose_name_plural': 'Взаимодействия'},
        ),
        migrations.AlterField(
            model_name='interplay',
            name='date_comm',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата взаимодействия'),
        ),
    ]
