# Generated by Django 3.0.5 on 2021-03-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210303_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interplay',
            options={'ordering': ['-date_comm'], 'verbose_name': 'Взаимодействие', 'verbose_name_plural': 'Взаимодействия'},
        ),
        migrations.AlterField(
            model_name='interplay',
            name='rating',
            field=models.BooleanField(null=True, verbose_name='Оценка взаимодействия'),
        ),
    ]
