# Generated by Django 3.0.5 on 2021-03-09 15:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210306_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interplay',
            name='descript',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='project',
            name='descript',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация о проекте'),
        ),
    ]
